import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./_components/layouts/Header";
import { Footer } from "./_components/layouts/Footer";
import { Noto_Sans_JP } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NotoSansJP = Noto_Sans_JP({ weight: "400", subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${NotoSansJP.className} bg-[#F8F8F8]`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
